name: flutter_boiler_plate
description: A flutter boiler plate for initial project setup

version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  ##firebase and auth
  firebase_core: ^1.2.0
  firebase_auth: ^1.2.0
  #firebase_crashlytics: ^0.4.0+1
  #firebase_analytics: ^7.0.1
  #flutter_facebook_auth: ^2.0.2
  google_sign_in: ^5.0.3

  ##utils
  rxdart: ^0.27.0
  provider: ^5.0.0
  flutter_bloc: ^7.0.0
  get_it: ^7.1.3
  easy_localization: ^3.0.0
  flutter_secure_storage: ^4.2.0
  shared_preferences: ^2.0.5
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  ##UI
  cupertino_icons: ^1.0.3
  flutter_launcher_icons: ^0.9.0
  cached_network_image: ^3.0.0
  sura_flutter: ^0.2.0
  image_picker: ^0.7.5+2
  sentry: ^5.0.0

  ##network
  dio: ^4.0.0

  flutter_icons:
    git:
      url: https://github.com/adarsh-technocrat/flutter-icons.git
      branch: null-safety-migration
  toast:
    git:
      url: https://github.com/appdev/FlutterToast.git

dev_dependencies:
  hive_generator: ^1.1.0
  flutter_flavorizr: ^2.0.0
  build_runner: ^2.0.3
  flutter_test:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app-icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/languages/

  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-Regular.ttf
        - asset: assets/fonts/GoogleSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/GoogleSans-Medium.ttf
          weight: 500

    - family: PreahVihear
      fonts:
        - asset: assets/fonts/Preahvihear-Regular.ttf

flavorizr:
  app:
    android:
      flavorDimensions: "default"
    ios:

  flavors:
    dev:
      app:
        name: "Flutter Boilerplate Dev"
      android:
        applicationId: "com.chunleethong.flutter_boiler_plate.dev"

      ios:
        bundleId: "com.chunleethong.flutterBoilerPlate.dev"

    staging:
      app:
        name: "Flutter Boilerplate Staging"

      android:
        applicationId: "com.chunleethong.flutter_boiler_plate.staging"
      ios:
        bundleId: "com.chunleethong.flutterBoilerPlate.staging"
    prod:
      app:
        name: "Flutter Boilerplate"

      android:
        applicationId: "com.chunleethong.flutter_boiler_plate"
      ios:
        bundleId: "com.chunleethong.flutterBoilerPlate"
