name: Telegram Release Apk
on:
  push:
    branches:
      - build
jobs:
  build:
    name: Build apk file and send to telegram group
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "1.22.5"
      - run: flutter pub get
      - run: flutter build apk --release --flavor dev
      - name: Rename Apk file
        run: cd build/app/outputs/flutter-apk && mv app-dev-release.apk flutter-boiler-plate.apk
      - name: send apk file
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.CHAT_ID }}
          token: ${{ secrets.BOT_TOKEN }}
          message: ${{github.event.head_commit.message}}
          document: build/app/outputs/flutter-apk/flutter-boiler-plate.apk
